// <auto-generated />
using System;
using FinanceHogar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceHogar.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414044722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generada");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_leida");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<decimal?>("PorcentajeUso")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_uso");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_alertas");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_alertas_categoria_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_alertas_estado");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_alertas_hogar_id");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_alertas_tipo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_alertas_usuario_id");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_global");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("boolean")
                        .HasColumnName("es_ingreso");

                    b.Property<Guid?>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("EsGlobal")
                        .HasDatabaseName("ix_categorias_es_global");

                    b.HasIndex("EsIngreso")
                        .HasDatabaseName("ix_categorias_es_ingreso");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_categorias_hogar_id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Color = "#2ECC71",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "money-bill",
                            IsDeleted = false,
                            Nombre = "Salario"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Color = "#3498DB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "plane",
                            IsDeleted = false,
                            Nombre = "Remesa"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Color = "#9B59B6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "store",
                            IsDeleted = false,
                            Nombre = "Negocio Propio"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Color = "#E67E22",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "handshake",
                            IsDeleted = false,
                            Nombre = "Trabajo Informal"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Color = "#1ABC9C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "users",
                            IsDeleted = false,
                            Nombre = "Tanda"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Color = "#E74C3C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "utensils",
                            IsDeleted = false,
                            Nombre = "Alimentacion"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Color = "#3498DB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "graduation-cap",
                            IsDeleted = false,
                            Nombre = "Educacion"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Color = "#E91E63",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "heartbeat",
                            IsDeleted = false,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Color = "#FF9800",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "bus",
                            IsDeleted = false,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Color = "#FFC107",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "bolt",
                            IsDeleted = false,
                            Nombre = "Servicios Basicos"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000011"),
                            Color = "#9C27B0",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "gamepad",
                            IsDeleted = false,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000012"),
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "piggy-bank",
                            IsDeleted = false,
                            Nombre = "Ahorro"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000013"),
                            Color = "#00BCD4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "users",
                            IsDeleted = false,
                            Nombre = "Cuota Tanda"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000014"),
                            Color = "#95A5A6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "ellipsis-h",
                            IsDeleted = false,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Comprobante")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comprobante");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_recurrente");

                    b.Property<DateOnly>("FechaGasto")
                        .HasColumnType("date")
                        .HasColumnName("fecha_gasto");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal?>("MontoEnUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_en_usd");

                    b.Property<Guid?>("ServicioBasicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servicio_basico_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_gastos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_gastos_categoria_id");

                    b.HasIndex("FechaGasto")
                        .HasDatabaseName("ix_gastos_fecha_gasto");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_gastos_hogar_id");

                    b.HasIndex("ServicioBasicoId")
                        .HasDatabaseName("ix_gastos_servicio_basico_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_gastos_usuario_id");

                    b.HasIndex("HogarId", "FechaGasto")
                        .HasDatabaseName("ix_gastos_hogar_id_fecha_gasto");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Hogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MonedaPrincipal")
                        .HasColumnType("integer")
                        .HasColumnName("moneda_principal");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("El Salvador")
                        .HasColumnName("pais");

                    b.Property<decimal>("PresupuestoMensualTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("presupuesto_mensual_total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hogares");

                    b.HasIndex("Departamento")
                        .HasDatabaseName("ix_hogares_departamento");

                    b.ToTable("Hogares", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.HogarUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("boolean")
                        .HasColumnName("es_administrador");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_hogar_usuarios");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_hogar_usuarios_hogar_id");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_hogar_usuarios_rol_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_hogar_usuarios_usuario_id");

                    b.HasIndex("HogarId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_hogar_usuarios_hogar_id_usuario_id");

                    b.ToTable("HogarUsuarios", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Ingreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_recurrente");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal?>("MontoEnUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_en_usd");

                    b.Property<Guid?>("RemesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("remesa_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_ingresos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_ingresos_categoria_id");

                    b.HasIndex("FechaIngreso")
                        .HasDatabaseName("ix_ingresos_fecha_ingreso");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_ingresos_hogar_id");

                    b.HasIndex("RemesaId")
                        .HasDatabaseName("ix_ingresos_remesa_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ingresos_usuario_id");

                    b.HasIndex("HogarId", "FechaIngreso")
                        .HasDatabaseName("ix_ingresos_hogar_id_fecha_ingreso");

                    b.ToTable("Ingresos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<decimal>("MontoGastado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_gastado");

                    b.Property<decimal>("MontoLimite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_limite");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_presupuestos_mensuales");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_presupuestos_mensuales_categoria_id");

                    b.HasIndex("Anio", "Mes")
                        .HasDatabaseName("ix_presupuestos_mensuales_anio_mes");

                    b.HasIndex("HogarId", "CategoriaId", "Anio", "Mes")
                        .IsUnique()
                        .HasDatabaseName("ix_presupuestos_mensuales_hogar_id_categoria_id_anio_mes");

                    b.ToTable("PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ComisionCobrada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("comision_cobrada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empresa");

                    b.Property<DateOnly>("FechaRecibida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_recibida");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NombreRemitente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_remitente");

                    b.Property<string>("NumeroConfirmacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_confirmacion");

                    b.Property<string>("PaisOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais_origen");

                    b.Property<string>("Proposito")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("proposito");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid")
                        .HasColumnName("receptor_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_remesas");

                    b.HasIndex("FechaRecibida")
                        .HasDatabaseName("ix_remesas_fecha_recibida");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_remesas_hogar_id");

                    b.HasIndex("ReceptorId")
                        .HasDatabaseName("ix_remesas_receptor_id");

                    b.ToTable("Remesas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Administrador del hogar con acceso total",
                            IsDeleted = false,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Miembro del hogar con acceso limitado",
                            IsDeleted = false,
                            Nombre = "Miembro"
                        });
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DiasAnticipacionNotificacion")
                        .HasColumnType("integer")
                        .HasColumnName("dias_anticipacion_notificacion");

                    b.Property<bool>("EstaVencido")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_vencido");

                    b.Property<DateOnly?>("FechaUltimoPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ultimo_pago");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("MontoPromedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_promedio");

                    b.Property<decimal>("MontoUltimoPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_ultimo_pago");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_proveedor");

                    b.Property<bool>("NotificacionActiva")
                        .HasColumnType("boolean")
                        .HasColumnName("notificacion_activa");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_cuenta");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_servicios_basicos");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("ix_servicios_basicos_fecha_vencimiento");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_servicios_basicos_hogar_id");

                    b.HasIndex("TipoServicio")
                        .HasDatabaseName("ix_servicios_basicos_tipo_servicio");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_servicios_basicos_usuario_id");

                    b.ToTable("ServiciosBasicos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cuota_mensual");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizador_id");

                    b.Property<int>("TotalParticipantes")
                        .HasColumnType("integer")
                        .HasColumnName("total_participantes");

                    b.Property<int>("TurnoActual")
                        .HasColumnType("integer")
                        .HasColumnName("turno_actual");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tandas");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_tandas_estado");

                    b.HasIndex("HogarId")
                        .HasDatabaseName("ix_tandas_hogar_id");

                    b.HasIndex("OrganizadorId")
                        .HasDatabaseName("ix_tandas_organizador_id");

                    b.ToTable("Tandas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.TandaParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CuotasPagadas")
                        .HasColumnType("integer")
                        .HasColumnName("cuotas_pagadas");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("FechaRecibio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recibio");

                    b.Property<bool>("HaRecibido")
                        .HasColumnType("boolean")
                        .HasColumnName("ha_recibido");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("integer")
                        .HasColumnName("numero_turno");

                    b.Property<Guid>("TandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tanda_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tanda_participantes");

                    b.HasIndex("TandaId")
                        .HasDatabaseName("ix_tanda_participantes_tanda_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tanda_participantes_usuario_id");

                    b.HasIndex("TandaId", "NumeroTurno")
                        .IsUnique()
                        .HasDatabaseName("ix_tanda_participantes_tanda_id_numero_turno");

                    b.HasIndex("TandaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_tanda_participantes_tanda_id_usuario_id");

                    b.ToTable("TandaParticipantes", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DUI")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dui");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_activo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("DUI")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_dui");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("EstaActivo")
                        .HasDatabaseName("ix_usuarios_esta_activo");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alertas_categorias_categoria_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Alertas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alertas_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Categorias")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_categorias_hogares_hogar_id");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gastos_categorias_categoria_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gastos_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.ServicioBasico", "ServicioBasico")
                        .WithMany("Pagos")
                        .HasForeignKey("ServicioBasicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gastos_servicios_basicos_servicio_basico_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gastos_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("ServicioBasico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.HogarUsuario", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hogar_usuarios_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Rol", "Rol")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hogar_usuarios_roles_rol_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hogar_usuarios_usuarios_usuario_id");

                    b.Navigation("Hogar");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Ingreso", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Ingresos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingresos_categorias_categoria_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingresos_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Remesa", "Remesa")
                        .WithMany("Ingresos")
                        .HasForeignKey("RemesaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingresos_remesas_remesa_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ingresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingresos_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("Remesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Presupuestos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_presupuestos_mensuales_categorias_categoria_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Presupuestos")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presupuestos_mensuales_hogares_hogar_id");

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Remesas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_remesas_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Receptor")
                        .WithMany("RemesasRecibidas")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_remesas_usuarios_receptor_id");

                    b.Navigation("Hogar");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_basicos_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ServiciosBasicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_basicos_usuarios_usuario_id");

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Tandas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tandas_hogares_hogar_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tandas_usuarios_organizador_id");

                    b.Navigation("Hogar");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.TandaParticipante", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Tanda", "Tanda")
                        .WithMany("Participantes")
                        .HasForeignKey("TandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tanda_participantes_tandas_tanda_id");

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tanda_participantes_usuarios_usuario_id");

                    b.Navigation("Tanda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Hogar", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Categorias");

                    b.Navigation("HogarUsuarios");

                    b.Navigation("Presupuestos");

                    b.Navigation("Remesas");

                    b.Navigation("Tandas");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Rol", b =>
                {
                    b.Navigation("HogarUsuarios");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("HogarUsuarios");

                    b.Navigation("Ingresos");

                    b.Navigation("RemesasRecibidas");

                    b.Navigation("ServiciosBasicos");
                });
#pragma warning restore 612, 618
        }
    }
}
