// <auto-generated />
using System;
using FinanceHogar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceHogar.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PorcentajeUso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Estado");

                    b.HasIndex("HogarId");

                    b.HasIndex("Tipo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EsGlobal");

                    b.HasIndex("EsIngreso");

                    b.HasIndex("HogarId");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Color = "#2ECC71",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "money-bill",
                            IsDeleted = false,
                            Nombre = "Salario"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Color = "#3498DB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "plane",
                            IsDeleted = false,
                            Nombre = "Remesa"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Color = "#9B59B6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "store",
                            IsDeleted = false,
                            Nombre = "Negocio Propio"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Color = "#E67E22",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "handshake",
                            IsDeleted = false,
                            Nombre = "Trabajo Informal"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Color = "#1ABC9C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = true,
                            Icono = "users",
                            IsDeleted = false,
                            Nombre = "Tanda"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Color = "#E74C3C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "utensils",
                            IsDeleted = false,
                            Nombre = "Alimentacion"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Color = "#3498DB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "graduation-cap",
                            IsDeleted = false,
                            Nombre = "Educacion"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Color = "#E91E63",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "heartbeat",
                            IsDeleted = false,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Color = "#FF9800",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "bus",
                            IsDeleted = false,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Color = "#FFC107",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "bolt",
                            IsDeleted = false,
                            Nombre = "Servicios Basicos"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000011"),
                            Color = "#9C27B0",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "gamepad",
                            IsDeleted = false,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000012"),
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "piggy-bank",
                            IsDeleted = false,
                            Nombre = "Ahorro"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000013"),
                            Color = "#00BCD4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "users",
                            IsDeleted = false,
                            Nombre = "Cuota Tanda"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000014"),
                            Color = "#95A5A6",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsGlobal = true,
                            EsIngreso = false,
                            Icono = "ellipsis-h",
                            IsDeleted = false,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comprobante")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaGasto")
                        .HasColumnType("date");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("integer");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoEnUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServicioBasicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FechaGasto");

                    b.HasIndex("HogarId");

                    b.HasIndex("ServicioBasicoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("HogarId", "FechaGasto");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Hogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MonedaPrincipal")
                        .HasColumnType("integer");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("El Salvador");

                    b.Property<decimal>("PresupuestoMensualTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Departamento");

                    b.ToTable("Hogares", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.HogarUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HogarId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("HogarId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("HogarUsuarios", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Ingreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("integer");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoEnUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RemesaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FechaIngreso");

                    b.HasIndex("HogarId");

                    b.HasIndex("RemesaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("HogarId", "FechaIngreso");

                    b.ToTable("Ingresos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoGastado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoLimite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Anio", "Mes");

                    b.HasIndex("HogarId", "CategoriaId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PresupuestosMensuales", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ComisionCobrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaRecibida")
                        .HasColumnType("date");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreRemitente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroConfirmacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaisOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Proposito")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FechaRecibida");

                    b.HasIndex("HogarId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Remesas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Administrador del hogar con acceso total",
                            IsDeleted = false,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Miembro del hogar con acceso limitado",
                            IsDeleted = false,
                            Nombre = "Miembro"
                        });
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiasAnticipacionNotificacion")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaVencido")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaUltimoPago")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MontoPromedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoUltimoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NotificacionActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("HogarId");

                    b.HasIndex("TipoServicio");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ServiciosBasicos", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("integer");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalParticipantes")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoActual")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("HogarId");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Tandas", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.TandaParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuotasPagadas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRecibio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HaRecibido")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("integer");

                    b.Property<Guid>("TandaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TandaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TandaId", "NumeroTurno")
                        .IsUnique();

                    b.HasIndex("TandaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("TandaParticipantes", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DUI")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DUI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EstaActivo");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Alertas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Categorias")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.ServicioBasico", "ServicioBasico")
                        .WithMany("Pagos")
                        .HasForeignKey("ServicioBasicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("ServicioBasico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.HogarUsuario", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Rol", "Rol")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HogarUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hogar");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Ingreso", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Ingresos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Remesa", "Remesa")
                        .WithMany("Ingresos")
                        .HasForeignKey("RemesaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ingresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("Remesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Presupuestos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Presupuestos")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Remesas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Receptor")
                        .WithMany("RemesasRecibidas")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hogar");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ServiciosBasicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Hogar", "Hogar")
                        .WithMany("Tandas")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hogar");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.TandaParticipante", b =>
                {
                    b.HasOne("FinanceHogar.Domain.Entities.Tanda", "Tanda")
                        .WithMany("Participantes")
                        .HasForeignKey("TandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceHogar.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tanda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Hogar", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Categorias");

                    b.Navigation("HogarUsuarios");

                    b.Navigation("Presupuestos");

                    b.Navigation("Remesas");

                    b.Navigation("Tandas");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Remesa", b =>
                {
                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Rol", b =>
                {
                    b.Navigation("HogarUsuarios");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.ServicioBasico", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Tanda", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("FinanceHogar.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("HogarUsuarios");

                    b.Navigation("Ingresos");

                    b.Navigation("RemesasRecibidas");

                    b.Navigation("ServiciosBasicos");
                });
#pragma warning restore 612, 618
        }
    }
}
